[book]
title = "Go gRPC 简明指南"
authors = ["jergoo"]
description = "Go gRPC Tutorial"
language = "zh"
multilingual = false
src = "src/docs"

[build]
build-dir = "docs"

[preprocessor.pagetoc]
[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js  = ["theme/pagetoc.js"]
